const express = require('express');
const router = express.Router();
const Receipt = require('../models/Receipt');

// 1. CHANGE THIS LINE (Add the curly braces around cloudinary)
const { cloudinary } = require('../cloudConfig'); // or '../config/cloudinary' depending on your file name

router.post('/generate', async (req, res) => {
  try {
    const { signature, ...receiptData } = req.body;
    let signatureUrl = signature; // Already uploaded?

    if (signature && signature.startsWith("data:image")) {
       const uploadRes = await cloudinary.uploader.upload(signature, {
        folder: "Roomify/signatures",
      });
      signatureUrl = uploadRes.secure_url;
    }

    // Explicitly create the object to ensure it's "flat"
    const newReceipt = new Receipt({
      owner: receiptData.owner,
      ownerId: receiptData.ownerId,
      requestId: receiptData.requestId,
      receipt_no: receiptData.receipt_no, // THIS IS THE KEY
      date: receiptData.date,
      tenant_name: receiptData.tenant_name,
      property_address: receiptData.property_address,
      rent_amount: receiptData.rent_amount,
      charges: receiptData.charges,
      total_amount: receiptData.total_amount,
      signature: signatureUrl
    });

    const saved = await newReceipt.save();
    res.status(201).json({ success: true, receipt: saved });

  } catch (err) {
    console.error("❌ Error:", err.message);
    res.status(400).json({ success: false, message: err.message });
  }
});
router.get('/request/:requestId', async (req, res) => {
  try {
    // We find the receipt linked to this specific booking request
    const receipt = await Receipt.findOne({ requestId: req.params.requestId });

    if (!receipt) {
      return res.status(404).json({ message: "Receipt not generated by owner yet." });
    }

    res.status(200).json(receipt);
  } catch (err) {
    console.error("Error fetching receipt:", err.message);
    res.status(500).json({ message: "Internal Server Error" });
  }
});
module.exports = router;